### ISSUE TITLE
Terminal behavior options

### ISSUE THREAD

**Issue by gkdgoutam** [elementary/code#836] opened 2020-06-30 09:12 UTC
Hello,

I am using `Code` and so far liking for its simplicity. One good feature is that I can add extension `Terminal`. I suppose that this Terminal is the default Terminal which comes with the OS. However it would be much nicer to open the terminal in the current directory in which the current file is opened. To explain further, lets say I opened two files  `file1` from `directory1` and `file2` from `directory2` . When I open `Terminal`,  if the current file is `file1` then the terminal should be opened at `directory1` and if the current file is `file2` then the terminal should be opened at `directory2`. I think this would improve productivity of the user as well as popularity of the editor.

**Comment by jeremypw** [comment] 2020-06-30 17:26
This is a duplicate of #58. There was a PR to fix this - https://github.com/elementary/code/pull/637 - but it had some unresolved issues and was closed as current thinking is to retire the Terminal plugin in favour of something more specifically focused on code development.  The terminal plugin is not, in fact, the same as the Terminal app (which is why it has fewer features) although it is based on the same terminal library.  There is a PR #810 that goes some way towards fixing the issue in a simpler way by providing a context menu option to change the terminal working directory to that of the current document.  Another simpler fix would be to provide a menu entry on the document context menu to "Open Terminal here" that opens the Terminal app, in a similar way to Files.

**Comment by jeremypw** [comment] 2024-12-06 12:55
There have been changes that hopefully meet your needs since this was raised.


1) Changing the active project automatically changes the terminal to the appropriate build directory (the relative build path is set in Preferences/Behaviour)
2) There is a context menu item on folders in the sidebar to change the terminal to that path.

I hope this satisfies this issue so closing.  Please feel free to re-open if there are outstanding matters.

**Closed by jeremypw** 2024-12-06 12:55 UTC
Labels: Status: Duplicate
