### ISSUE TITLE
Zoom button styling backwards on RTL

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#595] opened 2018-11-27 22:12 UTC
Just like #594 but for the zoom buttons in the popover.

![2018-11-27 14 58 28](https://user-images.githubusercontent.com/611168/49115040-e6e9ee80-f256-11e8-9100-c4ebcb4ef23a.png)

**Comment by danrabbit** [comment] 2018-12-04 00:52
Closing as a duplicate of https://github.com/elementary/stylesheet/issues/454

**Closed by danrabbit** 2018-12-04 00:52 UTC
Labels: i18n
