### ISSUE TITLE
Add option to turn off 'follow last tab'.

### ISSUE THREAD

**Issue by polokasu** [elementary/code#590] opened 2018-11-18 20:34 UTC

**Comment by cassidyjames** [comment] 2018-12-04 20:34
@polokasu could you provide more information describing what you expect to happen or what current behavior is not ideal in your eyes?

**Comment by polokasu** [comment] 2018-12-08 13:31
Need setting to deactivate the previous restoring tab when opening application (again).

**Comment by cassidyjames** [comment] 2018-12-10 22:19
@polokasu thanks! I believe this is a duplicate of https://github.com/elementary/code/issues/473, then. If not, feel free to let me know and we can re-open this.

**Closed by cassidyjames** 2018-12-10 22:19 UTC
Labels: Status: Duplicate
