### ISSUE TITLE
Right clicking the file in folder manager opens the file.

### ISSUE THREAD

**Issue by arshubham** [elementary/code#384] opened 2018-03-29 11:57 UTC
Right clicking the file in folder manager opens the file. Sometimes I only want to right click on the file name to delete it. In code it opens the file and and on delete it shows the yellow alert bar that the file was deleted, do I want to save it. Same with rename. 

I am using latest master from git.

Video:
https://shubhamarora.in/nextcloud/index.php/s/25dMaS7oJPSZQDe

**Comment by davidmhewitt** [comment] 2018-05-18 17:31
This is caused by `Granite.SourceList`, there is already a bug open there to fix this behaviour. I recommend tracking that bug here: https://github.com/elementary/granite/issues/9

Closing this as it can't be fixed in code.

**Closed by davidmhewitt** 2018-05-18 17:31 UTC
