### ISSUE TITLE
Language Server Protocol for Code

### ISSUE THREAD

**Issue by ctieben** [elementary/code#562] opened 2018-11-01 11:48 UTC
Hi,

first of all thanks for the development of elementary and all tools around it.

I like to ask if its possible to integrate the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/) into code.

This will add some nice features like:
- Syntax based code completion
- Jump between declaration and definition
- Find references and calls
- ...

This could be used for a better support of [C/C++](https://clang.llvm.org/extra/clangd.html) and [Rust](https://rls.booyaa.wtf/) for example.

**Comment by davidmhewitt** [comment] 2018-11-01 11:51
Hi - Thanks for the bug report. This is a duplicate of #220 

Closing this issue so we can track it in just one place.

**Closed by davidmhewitt** 2018-11-01 11:51 UTC
Labels: Status: Duplicate
