### ISSUE TITLE
Plugin: Compile and Execute

### ISSUE THREAD

**Issue by Jason5679** [elementary/code#736] opened 2019-12-02 20:58 UTC
Right now I am programming with Geany because
because I can compile directly from the text editor.
It's easy with a simple shortcut. I do not need to enter something at
 the terminal. I think a plugin could easily accomplish this task.

**Comment by danrabbit** [comment] 2021-04-21 18:11
closing as a duplicate of #939

**Closed by danrabbit** 2021-04-21 18:11 UTC
Labels: Status: Confirmed
