### ISSUE TITLE
Code do not keep files not saved open

### ISSUE THREAD

**Issue by adrianosaaquino** [elementary/code#607] opened 2018-12-19 15:38 UTC
Open code, new file
Type some text
Close code

There is no warning to save file and on open code, the file is not restored like scratch feature.

I try to install scratch-text-editor in Juno but is impossible.

**Comment by jeremypw** [comment] 2018-12-19 16:20
This is a duplicate of #524, for which there is an open PR fixing it.

**Closed by jeremypw** 2018-12-19 16:20 UTC

**Comment by adrianosaaquino** [comment] 2018-12-19 17:31
Thank you for the feedback.
