### ISSUE TITLE
FormatBar styling backwards on RTL

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#594] opened 2018-11-27 22:09 UTC
I'm not sure if this if for all linked buttons across the stylesheet, or specific to here. But the styling doesn't look to be working properly in CSS, as the first button gets the "left" styling, the last button gets the "right" styling, even though the order is reversed.

**Comment by cassidyjames** [comment] 2018-11-27 22:10
![2018-11-27 15 00 35](https://user-images.githubusercontent.com/611168/49114926-9f636280-f256-11e8-8535-11047cb72e6b.png)

**Comment by danrabbit** [comment] 2018-12-04 00:53
Closing as a duplicate of https://github.com/elementary/stylesheet/issues/454

**Closed by danrabbit** 2018-12-04 00:53 UTC
Labels: i18n
