### ISSUE TITLE
Terminal plug makes app crash when another window opens

### ISSUE THREAD

**Issue by Philip-Scott** [elementary/code#75] opened 2017-05-08 03:21 UTC

**Comment by jeremypw** [comment] 2017-06-13 15:10
Open app with two tabs and with Terminal plugin installed.  It need not be open.  Right-click on a tab and select "Open in New Window".  App crashes.

**Comment by davidmhewitt** [comment] 2018-10-20 12:44
I can't reproduce this, so closing for now. Can be re-opened if people can still re-produce it.

**Closed by davidmhewitt** 2018-10-20 12:44 UTC
Labels: Priority: High, Status: Confirmed
