### ISSUE TITLE
Auto switch theme with the rest of the system

### ISSUE THREAD

**Issue by MobileAZN** [elementary/code#1201] opened 2022-07-06 15:09 UTC
### Problem

Have Code auto switch it's theme following the system Appearance selection (Sunrise to SunSet or the set times).  I understand there are currently 3 themes.

### Proposal

A checkbox to automatically change the theme depending on time..  I am unsure of how I would implement the theme chooser for each time change.  A context menu would solve this,  however I feel that is hidden to the user, has frictio,n and doesn't keep it simple.

**Comment by jeremypw** [comment] 2022-07-06 16:58
Thanks for the report but closing as a duplicate of #902.  PR #1192 has been proposed to fix this.

**Closed** 2022-07-06 17:06 UTC
Labels: Status: Duplicate
