### ISSUE TITLE
Git GUI for making commits

### ISSUE THREAD

**Issue by ghost** [elementary/code#1200] opened 2022-06-25 15:20 UTC
### Problem

I use this software on a daily basis, it would be really cool to have an integrated Git GUI for comitting stuff. Shouldn't be very hard to have something basic.

### Proposal

A git GUI similar to VScode VCS or github desktop.

**Comment by jeremypw** [comment] 2022-06-26 07:30
There is an open discussion regarding improving Git support. I would be happy to review any PR implementing this feature.

**Comment by dragonDScript** [comment] 2022-06-26 11:14
I would be happy to make some progress on the issue when I have time (e.g. make an API)

**Comment by aitor-gomila** [comment] 2023-03-29 20:15
When I created this issue, I was an idiot. Time goes by very quickly :')

**Comment by colinkiama** [comment] 2023-11-19 20:06
@jeremypw do you mind if I have a go at this?

**Comment by jeremypw** [comment] 2023-11-20 10:11
@colinkiama Just noticed this is essentially a duplicate of #502 which has been in the related projects for quite some time.  To simplify things I will mark this as "Duplicate" and ask that you link your work to the primary issue and project (https://github.com/elementary/code/projects/2).  It would be very good to have some progress on this and I would certainly be willing to review your PR.  I would suggest perhaps mocking up a UI first and getting some input from @danirabbit to ensure that we stay in line with the elementary aesthetic.  As there are several potential Git/Github actions that could be implemented in future maybe a project action menu button somewhere in the sidebar?

**Comment by jeremypw** [comment] 2023-11-20 10:12
Duplicate of #502

**Closed by jeremypw** 2023-11-20 10:12 UTC
Labels: Status: Duplicate
