### ISSUE TITLE
Code crash immediately after start

### ISSUE THREAD

**Issue by xtelcz** [elementary/code#664] opened 2019-04-13 20:49 UTC
Does not matter, if run from App menu or from terminal, Code always crash immediately after start. The app window just blink for a moment.
`petr@UX410:~$ io.elementary.code
** GtkSourceView:ERROR:gtksourcecontextengine.c:5543:update_syntax: assertion failed: (g_slist_length (ce->priv->invalid) <= 1)
Aborted`
I have tried clean up temp, uninstall/re-install Code app.

**Comment by jeremypw** [comment] 2021-12-11 18:02
Closing this now as Code is much changed since this was opened and no-one has confirmed it.  Please re-open if this is still happening with a current version of Code.

**Closed by jeremypw** 2021-12-11 18:02 UTC
