### ISSUE TITLE
Opening new window duplicates opened Projects Folder

### ISSUE THREAD

**Issue by RMcNeely** [elementary/code#1152] opened 2021-12-08 18:05 UTC
### What Happened?

When you have multiple windows of Code open they duplicate the open project folders in the dropdown.

### Steps to Reproduce

1. Open Code, add a project folder
2. Open a new window of Code, notice it has your project folder already listed in the sidebar.
3. Click on the Projects dropdown, you can see that the same project you opened in your original folder is now there twice.

### Expected Behavior

The projects drop down should show the same projects as the sidebar instead of repeating projects

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2021-12-08 18:26
Thanks for reporting, but closing as duplicate of #1141

**Closed by jeremypw** 2021-12-08 18:26 UTC
