### ISSUE TITLE
LSP support

### ISSUE THREAD

**Issue by aitor-gomila** [elementary/code#1312] opened 2023-05-03 20:24 UTC
### Problem

Code doesn't autocomplete code for many languages

### Proposal

Supporting LSP will bring a large range of language support

**Comment by jeremypw** [comment] 2023-05-04 08:10
This is a duplicate of #220.  Despite being an old and much desired feature no-one has succeeded in implementing it yet. Maybe time to revisit it.

**Closed by jeremypw** 2023-05-04 08:10 UTC
