### ISSUE TITLE
Code is not following .editorconfig properties

### ISSUE THREAD

**Issue by onerbs** [elementary/code#719] opened 2019-10-21 12:28 UTC
Yes, I have searched open and closed issues for duplicates.

I have a .editorconfig file in my project defining indentation in 4 spaces but Code has a funny (and unwanted) behaviour, see:

![Code Behaviour](https://user-images.githubusercontent.com/10482133/67204243-af39e700-f3d2-11e9-9b2b-ce838eac450c.png)
![.editorconfig](https://user-images.githubusercontent.com/10482133/67204371-fa53fa00-f3d2-11e9-9a1c-ac5081cdd8b9.png)
Result:
![Result](https://user-images.githubusercontent.com/10482133/67204400-03dd6200-f3d3-11e9-94a6-7afaa581adbe.png)

- [ YES ] I have EditorConfig plugin enabled
- [ NO ] I'm using the latest version from git that I've manually compiled
- [ YES ] I'm using the latest released stable version

I would expect that .editorconfig properties override Code own behaviour.

**Comment by jeremypw** [comment] 2021-08-06 14:27
@onerbs Is this still happening for you? I am getting the expected 4 space tab with the current version of Code.

**Comment by jeremypw** [comment] 2023-01-21 16:43
I am closing this as it really needs a more specific description with steps to reproduce.  Note that (1) the editorconfig plugin needs to be activated to see the required behaviour and (2) the settings in the AppMenu are global and do not reflect any overriding setting that might be active due to the editorconfig file in a particular project (which only applies to that project)

**Closed by jeremypw** 2023-01-21 16:43 UTC
