### ISSUE TITLE
Don't show empty sidebar (on startup).

### ISSUE THREAD

**Issue by quequotion** [elementary/code#302] opened 2018-01-11 10:36 UTC
Whenever Code starts, the sidebar is always displayed--even if there's nothing in it.

It can be closed by loading and then clearing something, such as a folder, but I think it would be sexier if it never appeared while empty.

[![Screenshot_from_2018-01-11_19.29.41.png](https://s9.postimg.org/iiu8itcrz/Screenshot_from_2018-01-11_19.29.41.png)](https://postimg.org/image/ojrxfvze3/)

**Comment by codygarver** [comment] 2018-01-11 10:51
Closing as duplicate of #258

**Comment by jeremypw** [comment] 2019-12-30 17:34
Now the sidebar has an inline toolbar it might be worth reconsidering this as it is no longer obvious how to add a folder to an empty, autoclosed sidebar.  One idea would be to add a pseudo folder "Open Tabs" to keep the sidebar open and useful.

**Comment by cassidyjames** [comment] 2020-04-09 17:44
Eh, this doesn't really seem like the same issue. #567 was already filed.

**Closed by cassidyjames** 2020-04-09 17:44 UTC
