### ISSUE TITLE
Cannot create a new file

### ISSUE THREAD

**Issue by IndrjoDedej** [elementary/code#682] opened 2019-06-21 10:53 UTC
Here are the steps to reproduce the problem.
1. Click on the Code icon everywhere it is.
2. Click on "New File".
3. Nothing or sometimes crashes.

![Schermata da 2019-06-21 12-51-52](https://user-images.githubusercontent.com/46417157/59917873-66255680-9423-11e9-83b7-3a2974cc7fb0.png)

**Comment by cassidyjames** [comment] 2019-06-26 22:03
I cannot reproduce.this. Did you possibly open Code as root from Terminal, causing permissions errors? Can you please open Code with debugging messages (`G_MESSAGES_DEBUG=all io.elementary.code`) from Terminal, reproduce the issue, and paste the output here?

**Comment by IndrjoDedej** [comment] 2019-06-27 10:50
The output from the terminal is:
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
indrjo@puter:~$ G_MESSAGES_DEBUG=all io.elementary.code
(io.elementary.code:6875): Gtk-DEBUG: 12:19:44.571: Connecting to session
manager
[FATAL 12:19:49.194986] DocumentView.vala:151: Errore nell'aprire il file
«/home/indrjo/.local/share/io.elementary.code/unsaved/Text file from
2019-06-27 12:19:49:194735»: Permesso negato
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I'm sorry because the output is in Italian, but here are some translations:
Errore nell'aprire il file = Error in opening the file/ Cannot open the file
Permesso negato = Access deinied

I tried:
sudo rm -rf /home/indrjo/.local/share/io.elementary.code
and everithing seems working properly.

But this behaviour is very strange, gedit has never behaved in such a way,
I constantly switched form normal user and superuser and I have not
encountered any issue. You should add some code which controls such files
and make sure them to not change permissions.

Indrjo Dedej

**Comment by tintou** [comment] 2019-06-27 12:14
duplicate of  #202

**Comment by tintou** [comment] 2019-06-27 12:14
duplicate of  #202

**Closed by tintou** 2019-06-27 12:14 UTC
Labels: Status: Incomplete
