### ISSUE TITLE
Files that require administrator privileges should ask for password 

### ISSUE THREAD

**Issue by D0J0P** [elementary/code#695] opened 2019-07-26 22:14 UTC
When coming across a file in Files that opens in Code, and requires administrator privileges to edit, I'd have to open up Files as Administrator, then reopen the file in order to edit it. It would be better if the file in Code would ask me to enter my password so I can get administrator privileges right away to access it.

**Comment by jeremypw** [comment] 2019-07-27 09:44
Thanks for the report. This is related to https://github.com/elementary/files/issues/165 and I do not think it is really within Code scope to fix.

**Comment by danrabbit** [comment] 2021-04-21 18:09
Closing as a duplicate of #679

**Closed by danrabbit** 2021-04-21 18:09 UTC
Labels: Status: Out of Scope
