### ISSUE TITLE
IntelliSense/Autocomplete?

### ISSUE THREAD

**Issue by WattanaGaming** [elementary/code#588] opened 2018-11-16 20:59 UTC
Will there be a autocomplete system?

**Comment by diegomagela** [comment] 2020-04-05 20:55
It will be a good feature. I'm trying to use just Code, but without IntelliSense I lost in productivity. I'm coding python.

**Comment by danrabbit** [comment] 2021-04-21 18:13
Closing as a duplicate of #220

**Closed by danrabbit** 2021-04-21 18:13 UTC
