### ISSUE TITLE
Style preference not respected.

### ISSUE THREAD

**Issue by ChildishGiant** [elementary/code#1074] opened 2021-06-24 15:12 UTC
## What Happened
When opening code with dark style selected the app is still light.

## Expected Behavior
Code should follow the system theme unless the user changes it.

## Steps to Reproduce
1. Set system style to dark
2. Open code

## Platform Information
* elementaryos-6.0-daily.20210624
* ThinkPad T460 
*  Kernel: 5.8.0-59-generic

**Comment by cassidyjames** [comment] 2021-08-10 04:56
Duplicate of #902. This is a let peeve of mine as well but last I looked into it, the style scheme code was scary. Maybe after the 6.0 release we can get some cleanup in and enable this.

**Closed by cassidyjames** 2021-08-10 04:56 UTC
