### ISSUE TITLE
Terminal should always be available if you've opened a project folder

### ISSUE THREAD

**Issue by colinkiama** [elementary/code#873] opened 2020-09-05 10:51 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Feature
**Is your feature request related to a problem? Please describe.**

I get frustrated when I'm not able to access the terminal when I don't have any files open in code.

**Describe the solution you'd like**
I would like the terminal to always be available when I've loaded a project folder. It should open in the project root.

**Comment by jeremypw** [comment] 2020-09-05 12:39
I presume you mean the terminal plugin. It has been suggested that this be removed altogether and replaced with more targeted functionality, which will probably include an easy way to open the Terminal app at the appropriate location.  However, I just tried opening the terminal plugin with a project folder open but no documents open and it seemed to work OK:
![Screenshot from 2020-09-05 13 36 00](https://user-images.githubusercontent.com/10513844/92305196-e5e20700-ef7c-11ea-9e73-839e5774d32b.png)
This is using the latest master version.

**Comment by colinkiama** [comment] 2020-09-05 16:14
I'm using the latest release from the OS. Version 3.4.1. Notice that the terminal plugin button isn't visible on the top right. (It appears again as soon as I select a file).
![Screenshot from 2020-09-05 17-09-15](https://user-images.githubusercontent.com/16501024/92309163-146eda80-ef9b-11ea-8f66-b5a331e1f95b.png)

I'll stick with using the terminal instead of the terminal plugin for now.

**Comment by jeremypw** [comment] 2020-09-05 18:23
Have you tried with the light theme? Maybe the icon is obscured??  There is no obvious commit since the last release that would affect this (judging by their titles) but I guess they may have had a side effect.

**Comment by colinkiama** [comment] 2020-09-05 18:41
I've just tried it with light theme now. I still have the same issue.

**Comment by jeremypw** [comment] 2024-01-11 17:06
> I would like the terminal to always be available when I've loaded a project folder. It should open in the project root.

This is essentially a duplicate of #283

**Closed by jeremypw** 2024-01-11 17:06 UTC
Labels: Status: Duplicate
