### ISSUE TITLE
Unusably slow with not so big files

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/code#409] opened 2018-04-28 08:27 UTC
Hi.
I tried to open a 20k text file, without any plugins enabled, and Scratch couldn't handle it and it crashed.
15k text files it can barely work with, with long freeze periods, but it doesn't crash.

Version: `2.4.1~r1825-0+pkg97~ubuntu0.4.1.2`

**Comment by alexgleason** [comment] 2018-10-01 21:13
In the meantime is there a way to reset Scratch (eg delete its configuration) so it can be opened again? At the moment the whole program is unusable and I have to use a different text editor because it keeps trying to load the file every time it starts.

**Comment by alexgleason** [comment] 2018-10-02 16:35
Everyone in this thread has been using the name "Scratch" so I'm guessing we're commenting about Loki (I am).

**Comment by dcharles525** [comment] 2018-10-05 15:56
I can confirm this in Juno Beta2 (code) I will have about 6 files open at a time the biggest being 10kb.

**Comment by bruhosabto** [comment] 2018-12-23 13:31
Infelizmente depois da ultima atualização que recebi, o code tem tido muitos travamentos, em uma dessas ocorrências foi necessário fazer reboot no pc, espero que receba logo uma correção.

**Comment by vaclavhlobil** [comment] 2019-01-05 20:51
Same with Code on Juno.

**Comment by jeremypw** [comment] 2019-01-06 13:16
In order to help investigating this, could you specify in each case which plugins are active and which operations are particularly affected.

**Comment by dcharles525** [comment] 2019-01-06 21:34
@jeremypw I disabled all of the plugins and still get a considerable stutter when tabbing over about 15-20 lines of code or editing large files (about 4-5 seconds, this occurs on my laptop, desktop, and work desktop). Since its been awhile since I looked at this issue I will do more intensive testing this week while at work, where I was experiencing the bulk of the issues and report back something more conclusive.

**Comment by dcharles525** [comment] 2019-01-08 19:22
Ok so with Brackets Completion, Highlight Word Selection, Preserve Indent, and Words Completion on I seem to be having the lag issue pretty consistently. For example a file about 2000 lines, I moved a block of 100 lines into a if statement and when cutting and pasting the editor lagged out for about 10-15 seconds. Also general performance is much worse with the plugins above enabled such as tabbing over lines or editing lines.

**Comment by jeremypw** [comment] 2023-07-07 17:08
I haven't noticed any unusual slowness using Code with 10 - 20 code files, some quite large, so closing.  Please reopen if the latest version of Code still has severe performance issues.  Note that some features such as "Autosave" and some plugins could cause noticeable slow down with low power cpus or slow disks.  Probably best to open a separate issue for each feature that causes a significant slow down.  Work can then be focussed on optimising that feature.

**Closed by jeremypw** 2023-07-07 17:08 UTC
