### ISSUE TITLE
Add Play button which compiles & runs the project

### ISSUE THREAD

**Issue by marbetschar** [elementary/code#793] opened 2020-04-20 08:27 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Feature

It would be great to have a Play button within Code which compiles and runs the current project (only if supported of course) - similar to what GNOME Builder does (see Screenshot below).

The missing Play button is what initially scared me away from Code when I started contributing to elementary, because I did not see an easy way to build & run my Vala code.

![builder](https://user-images.githubusercontent.com/392542/79730417-1a686580-82f1-11ea-9812-2181e9269b9d.png)

FWIW: If I remember correctly there was already some sort of discussion regarding the Play button - but I don't recall the outcome and I did not found an Issue or Pull Request in this repo for the topic.

**Comment by danrabbit** [comment] 2021-04-21 18:11
closing as a duplicate of #939

**Closed by danrabbit** 2021-04-21 18:11 UTC

**Comment by psydvl** [comment] 2021-05-01 19:18
@danrabbit, this issue is older, why are you close it instead of #939?

**Comment by danrabbit** [comment] 2021-05-02 02:53
@psydvl 939 has more examples of prior art
