### ISSUE TITLE
Make Install error: missing ".desktop" file 

### ISSUE THREAD

**Issue by yufelipeto** [elementary/code#279] opened 2017-11-21 16:06 UTC
Cmake shows an error while installing:
```
CMake Error at data/cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/home/yurefelipeto/Code/data/org.pantheon.scratch.desktop".
```

**Comment by cassidyjames** [comment] 2018-01-26 22:52
Can't reproduce here. @yufelipeto what OS are you on? Does this still occur?

**Comment by davidmhewitt** [comment] 2018-03-15 15:59
Closing as code no longer uses CMake.

Please let us know if there are still any issues with the new meson build system.

**Closed by davidmhewitt** 2018-03-15 15:59 UTC
Labels: Status: Incomplete
