### ISSUE TITLE
Large file freezes Code and is not easily closed

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [elementary/code#329] opened 2018-01-31 06:26 UTC
I've tried to open a large XML file (which is, despite being a huge single-line document, an correct textual file, I've successfully opened it in Vim), and Code froze, and I had to close it with "xkill" command.

However, the issue is that, when Code is opened the next time, that file is still trying to open, and there is no way to close the tab of the file before the application freezes.

Maybe we should somehow detect when file is taking too long to load, and then close it, and show an notification, like "file is invalid / file is too big", so that it doesn't completely freeze the application?

**Comment by jeremypw** [comment] 2018-01-31 08:37
Are you using the stable repository or the unstable (daily) one?  There have been a couple of commits since the last stable release that deal with files that fail to load (e.g. are not text documents).  In those cases a warning is given and that document will not be restored.  It is not clear what will happen in this case however as the file you mention is a valid text file.  Those commits only deal with loading the file.  If Code is hanging after that there may still be an issue.

**Comment by cassidyjames** [comment] 2018-02-23 23:18
Is this a duplicate of #5, or different?

**Comment by jeremypw** [comment] 2018-02-24 15:24
Both #5 and #21 have been closed due to PRs merged after the last stable release.  This seems to be the same issues.  Moreover Code will not now try to restore a document that previously failed to load.

**Closed by jeremypw** 2018-02-24 15:24 UTC
