### ISSUE TITLE
search should also search project files. not only the opened file.

### ISSUE THREAD

**Issue by kvdz** [elementary/code#491] opened 2018-08-13 07:33 UTC
when i code i would like to search for variables uses through out different classes. now i can't find them.

**Comment by micahilbery** [comment] 2018-08-13 15:18
Removing the bounty label as there is not yet a bounty for this issue.

**Comment by davidmhewitt** [comment] 2018-08-16 10:31
Closing as a duplicate of #418

**Closed by davidmhewitt** 2018-08-16 10:31 UTC
