### ISSUE TITLE
Spell Check not working for markdown files

### ISSUE THREAD

**Issue by rwlyonsjr** [elementary/code#634] opened 2019-02-04 01:58 UTC
I have been using code for writing markdown files and I am having a problem with spellcheck. When I open a new file, spellcheck works fine, but as soon as I save the file with the .md extension, spellcheck stops working. If anyone can point me to something I am missing that would be great.

I am using Elementary OS 5.0

**Comment by cassidyjames** [comment] 2019-11-09 07:26
Thanks for reporting this, and sorry about the massive delay in response. I've confirmed this, but it seems to be a duplicate of #234.

**Closed by cassidyjames** 2019-11-09 07:26 UTC
