### ISSUE TITLE
Right-clicking an item in the sidebar also opens it

### ISSUE THREAD

**Issue by cassidyjames** [elementary/code#465] opened 2018-06-13 18:55 UTC
It looks like we're not listening for just a left click

**Comment by davidmhewitt** [comment] 2018-06-13 19:15
This is a duplicate of (the admittedly closed #384 ), caused by https://github.com/elementary/granite/issues/9.

Currently working on a fix!

**Comment by cassidyjames** [comment] 2018-06-13 19:32
D'oh! Didn't think to look at closed issues. My bad. Thanks for looking into it!

**Closed** 2018-07-31 22:37 UTC
