### ISSUE TITLE
In dark mode, open code again in light color

### ISSUE THREAD

**Issue by raffeyang** [elementary/code#1357] opened 2023-07-21 14:24 UTC
### What Happened?

In dark mode, open code again in light color

### Steps to Reproduce

In dark mode, open code again in light color

### Expected Behavior

In dark mode, open code again in light color

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by jeremypw** [comment] 2023-07-21 15:45
It is not clear what the problem is, I am afraid.  Please add further detail.  I find that with the latest version of Code, the color scheme is saved on closing and restored on reopening, as expected.  The only reason for it to change is if you have it set to "follow system style" and you change the system style between closing and opening.

Do you want two Code windows open, one dark and one light mode perhaps?

**Closed** 2023-07-22 02:52 UTC
