### ISSUE TITLE
Emmet would be amazing

### ISSUE THREAD

**Issue by 0pendev** [elementary/code#396] opened 2018-04-20 09:41 UTC
Love your work guys. 

And I really like using elementary-code to write websites. The browser preview makes using elementary code great.

The only thing that is bothering me is its lack of an emmet implementation to write HTML faster.

I really hope a plugin could be done.

**Comment by ertoorule** [comment] 2019-02-05 22:22
No No! It would be crrrayzz!

**Comment by danrabbit** [comment] 2021-04-21 20:18
I think this is technically a duplicate of #36

**Closed by danrabbit** 2021-04-21 20:18 UTC
Labels: Priority: Wishlist
