### ISSUE TITLE
how using coding auto complete like a sublime, atom text editor & many other 

### ISSUE THREAD

**Issue by aacassandra** [elementary/code#555] opened 2018-10-28 00:06 UTC
Previously, I thank you. for all elementary os teams who have created this os with their creative ideas.

I personally really admire text editors like "CODE". because I have seen some features of text editors like sublime, atoms and more here. and this makes me easier to do work.

but there is one thing that gets stuck here. I have googled and read the "code" documentation on the site https://elementary.io/id/docs/code/reference#reference. none of which I can explain how to do auo completion docing like sublime, atom and other text editors

when I type "div" and click tab or enter it will change to <div class = ""> </ div> or something. I've tried changing the "plain text" menu to html or php but it doesn't produce anything.

Is there anyone who can give me a clue how "CODE" carries auto complete coding? thank you

**Comment by danrabbit** [comment] 2021-04-21 18:13
Closing as a duplicate of #220

**Closed by danrabbit** 2021-04-21 18:13 UTC
