### ISSUE TITLE
Scratch freezes on creating a new file if it's used by root first

### ISSUE THREAD

**Issue by Shnatsel** [elementary/code#339] opened 2018-02-23 23:15 UTC
I've only ever opened existing files in Scratch for a while. Then I've typed `sudo scratch-text-editor` in terminal. Now I'm trying to use Scratch again and it hangs with an immobile spinner every time I try to create a new file. Console output shows the following:

`[FATAL 02:10:02.670781] DocumentView.vala:113: Error opening file '/home/shnatsel/.local/share/scratch-text-editor/unsaved/Text file from 2018-02-24 02:10:02': Permission denied`

I've checked and turns out folder "/home/shnatsel/.local/share/scratch-text-editor/unsaved/" is indeed owned by root!

I'm on Loki, Scratch version `2.4.1~r1825-0+pkg97~ubuntu0.4.1.2`

**Comment by cassidyjames** [comment] 2018-02-23 23:16
Probably a dupe of #202?

**Closed** 2018-02-23 23:16 UTC
Labels: Status: Duplicate
