### ISSUE TITLE
Code opens and closes immediately

### ISSUE THREAD

**Issue by xayden** [elementary/code#585] opened 2018-11-16 10:50 UTC
Running it from terminal gives 
```
   ➜  ~ io.elementary.code 
    [FATAL 05:54:57.549480] [GLib] g_str_has_prefix: assertion 'str != NULL' failed
    [FATAL 05:54:57.550816] [GLib] g_str_has_prefix: assertion 'str != NULL' failed
    [1]    6094 segmentation fault  io.elementary.code
    ➜  ~ 
```
Here is the video https://www.reddit.com/r/elementaryos/comments/9xils7/code_opens_and_closes_immediately/

**Comment by davidmhewitt** [comment] 2018-11-16 10:51
Could this be related/a duplicate of #544?

**Comment by xayden** [comment] 2018-11-16 11:07
Works!

**Closed** 2018-11-16 11:07 UTC
