### ISSUE TITLE
Blank sidebar when no folder manager extension

### ISSUE THREAD

**Issue by jeremypw** [elementary/code#258] opened 2017-11-03 17:05 UTC
If the folder manager extension is activated a sidebar is added to the window.  If the folder manager extension is then deactivated the sidebar disappears.  However, on closing and reopening the app, a blank sidebar reappears (have to drag divider to 'close' it).

**Comment by davidmhewitt** [comment] 2018-03-23 11:15
@jeremypw I believe this will have been fixed in #350 by virtue of the fact we no longer have that extension. But maybe the outline plugin would cause it too. Are you still able to reproduce the issue?

I added some extra invisible by default code to `Pane.vala` that may help with this.

**Comment by davidmhewitt** [comment] 2018-05-20 17:09
Going to close this on the basis of no longer having that extension and not being able to reproduce it with the outline plugin.

**Closed by davidmhewitt** 2018-05-20 17:09 UTC
Labels: Status: Incomplete

**Comment by mikelo1** [comment] 2018-11-16 10:35
Hi,
I'm having the same blank sidebar as explained in this thread, but in the Juno release.
You guys can recreate the scenario if you have a Loki with the "folder manager" extension disabled in the Scratch, and then "upgrade" from Loki to Juno, running a fresh Juno installation but keeping all files in /home directory. You will find some settings missing, such as the folder manager in Code.
Since currently this feature belongs to the application core, I'm assuming that somewhere in the settings it remains disabled, and there is no option in the UI to enable it back.
Does anyone know any trick to enable it?
Thanks!
