### ISSUE TITLE
New Document does not work

### ISSUE THREAD

**Issue by rasmus91** [elementary/code#559] opened 2018-10-30 11:34 UTC
If i use the plank context menu to create a new document, the app opens and displays the attached error, and the tabs line is not displayed. If i click the 'plus' icon in the tabs, after opening a folder, nothing happens. So the only way i can type in new documents is by creating an empty file in the folder pane.

The text in the error says: 'The File "`<b>(null>)</b>`" can not be opened. It is an "unknown" filetype.'
![skaermbillede fra 2018-10-30 12-32-07](https://user-images.githubusercontent.com/2297739/47715478-316c5100-dc40-11e8-9ae5-e7f7ad3d5f84.png)

**Comment by rasmus91** [comment] 2018-11-03 14:20
I experimented with this on my Desktop computer as well, There, i can simply not replicate the issue.

**Comment by davidmhewitt** [comment] 2018-11-17 09:30
This sounds like a duplicate of https://github.com/elementary/code/issues/202 then.

It wouldn't have been possible for that folder to become owned as root without something running as root taking ownership of it (which was more than likely Code itself).

**Closed by davidmhewitt** 2018-11-17 09:30 UTC
